### ISSUE TITLE
win32 py3 UnicodeDecodeError

### ISSUE THREAD

**Issue by jayvdb** [aleGpereira/flake8-mock#3]
Installing on Windows Python 3.4 causes an error when using cp1252

```
Collecting flake8-mock
  Downloading flake8-mock-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-juvborbb\flake8-mock\setup.py", line 26, in <module>
        long_description=get_long_description(),
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-juvborbb\flake8-mock\setup.py", line 18, in get_long_description
        descr.append(f.read())
      File "c:\projects\flake8-putty\.tox\flakes-v250\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 100: character maps to <undefined>
```

https://ci.appveyor.com/project/jayvdb/flake8-putty/build/job/nd1dxsip79s7mc9r

**Comment by jayvdb** [comment]
Thx. Are you planning a release soon?

**Comment by aleGpereira** [comment]
Sorry for such delay. I've already uploaded a new version at https://pypi.python.org/pypi/flake8-mock/0.3

**Comment by jayvdb** [comment]
Thank you!
